spring:
  application:
    name: rabbitmq-test
  rabbitmq:
    host: 192.168.80.120
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-returns: true
server:
  port: 8889